name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.29

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install jsdom
        run: bun add -d jsdom

      - name: Run format write
        run: bun run format

      - name: Run format check
        run: bun run format:check

      - name: Run linter
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build
        run: bun run build
